### ISSUE TITLE
Improve temporary onboarding & unlock screen UI

### ISSUE THREAD

**Issue by rolznz** [getAlby/nostr-wallet-connect-next#10]
The current screens are missing copy and design. This is a temporary change to allow people to start testing NWC while we work on a full UI redesign.

**Comment by stackingsaunter** [comment]
@rolznz I did quick design improvements, [see here](https://www.figma.com/file/98bWDLs9dRVnYwW5ZVEqos/Nostr-Wallet-Connect?type=design&node-id=1254-5182&mode=design)

Added alternative dashboard card view but I don't think it's important at this moment.
Added apps for better discovery. It can be a seperate page or on dashboard below connections?
