### ISSUE TITLE
Add call to sign messages

### ISSUE THREAD

**Issue by bumi** [getAlby/nostr-wallet-connect-next#108]
For some use cases we need the signMessage call (like in [webln](https://www.webln.guide/building-lightning-apps/webln-reference/webln.signmessage)) 
It should be possible to pass an arbitrary message which is then signed by the node's key. 

this should be exposed through NWC similar to the other handle_* calls.

**Comment by rdmitr** [comment]
Both Greenlight and LDK have methods for that, so it shouldn't be too hard.

One question though. I see that in NWC the Handle* callbacks process NIP47 methods. However, there doesn't seem to be a method in NIP47 to sign arbitrary messages. Could you please elaborate a bit on how it should be exposed?

**Comment by bumi** [comment]
we will need to propose that as an addition to the NIP47 spec. 
regarding the request params and response I would use what we have in webln.

request:
```
  message: string
```

response:
```
  message: string;
  signature: string;
```

cc @rolznz does this make sense?

**Comment by rdmitr** [comment]
WIP PR: https://github.com/getAlby/nostr-wallet-connect-next/pull/124
