### ISSUE TITLE
Redeem onchain funds (LDK/Greenlight)

### ISSUE THREAD

**Issue by rolznz** [getAlby/nostr-wallet-connect-next#128]
For LDK and Greenlight it would be useful to be able to withdraw onchain funds (e.g. you want to move them to a different node after channel closure)

It should be able to use the same function as https://github.com/getAlby/nostr-wallet-connect-next/pull/57

**Comment by rdmitr** [comment]
I am not sure if I understood how to implement that properly — could you please take a look at the PR? https://github.com/getAlby/nostr-wallet-connect-next/pull/131

I branched it off from your redeem PR for Breez. I also merged the latest changes from master into it.

The corresponding PR to add the withdraw() method to glalby is here: https://github.com/getAlby/glalby/pull/9

**Comment by rolznz** [comment]
@rdmitr it looks good to me. We'll need close channel support in Greenlight and then add some buttons on the frontend to test it since channel management is not automated like Breez. I can do the UI.
