### ISSUE TITLE
Greenlight: close channel

### ISSUE THREAD

**Issue by rolznz** [getAlby/nostr-wallet-connect-next#132]
we need to be able to close channels to redeem onchain funds

This needs to be implemented in glalby first, and then we can consume them in nwc through glalby-go

**Comment by rdmitr** [comment]
PRs are up:

- glalby: https://github.com/getAlby/glalby/pull/10
- glalby-go: https://github.com/getAlby/glalby-go/pull/6
- nostr-wallet-connect-next: https://github.com/getAlby/nostr-wallet-connect-next/pull/138
