### ISSUE TITLE
Implement basic backup and restore for migrating LDK node

### ISSUE THREAD

**Issue by rolznz** [getAlby/nostr-wallet-connect-next#210]
There are cases where a user wants to move their LDK node (self-hosted to cloud or vice versa).

# Backup

## Backend endpoint
1. Verify the unlock password
1. Stop the node
2. Zip the NWC DB and the whole ldk/storage folder using the unlock password
3. Return the zip as a downloadable file as the response of the endpoint

## Frontend
1. See info about what will happen (the node will be stopped and you will receive a zip file. Do not start it again).
2. Press "confirm backup"
3. Re-enter unlock password and pass to backend endpoint
4. Zip file will be downloaded
5. Navigate to an instructions page on how to import with mnemonic and backup zip file (Note: the node has stopped at this point and without an instant redirect the user will be automatically redirected to the start page)

# Restore

## Backend endpoint
1. Accepts upload of encrypted backup file plus unlock password.
2. File will unzipped with the password and put the files in the correct location

## Frontend
1. Update LDK import flow to allow uploading the encrypted backup zip file before the /setup endpoint is called, along with passing the unlock password
2. After setup and import is successful, user should be guided to delete the backup file

Original ticket: https://github.com/getAlby/nostr-wallet-connect-next/issues/40

**Comment by rdmitr** [comment]
One question: why do we want password protection? Zip encryption is known to be flawed, unless the AES extension is used which is better but less universal and still does not encrypt metadata AFAIK.

**Comment by rdmitr** [comment]
Another question: if we are to backup NWC DB, which is a sqlite file, it is not enough to stop the node; the whole service needs to be shut down and the database needs to be closed. Otherwise we risk getting corrupt data.

Alternatively, I believe we could use sqlite online backup.

**Comment by rolznz** [comment]
@rdmitr 

> One question: why do we want password protection? Zip encryption is known to be flawed, unless the AES extension is used which is better but less universal and still does not encrypt metadata AFAIK.

I thought it would be slightly better to do this, then the file the user downloads is encrypted locally, but maybe it's not necessary right now? we will also instruct users to delete the file after they have imported it.

The encryption scheme only needs to be supported by the Go app to re-import it later.

> Another question: if we are to backup NWC DB, which is a sqlite file, it is not enough to stop the node; the whole service needs to be shut down and the database needs to be closed. Otherwise we risk getting corrupt data.

Good point. I think that would be safest. Do you see any issues with implementing it this way?

**Comment by rdmitr** [comment]
> The encryption scheme only needs to be supported by the Go app to re-import it later.

Alright, then we can encrypt the entire archive with any OK-ish block cipher. The benefit over ZIP encryption is that, once encrypted, the archive will look like a generic blob of data instead of an encrypted ZIP, and no metadata will be visible. Slightly more secure, slightly easier to implement 😄

We also need to keep in mind what it is that we want to safeguard our users against. If their password is compromised, neither ZIP nor custom encryption would help against a dedicated attacker. But encryption prevents — or makes much harder — accidental data leaks if the backup is not deleted by the client.

>> Another question: if we are to backup NWC DB, which is a sqlite file, it is not enough to stop the node; the whole service needs to be shut down and the database needs to be closed. Otherwise we risk getting corrupt data.

> Good point. I think that would be safest. Do you see any issues with implementing it this way?

The primary issue here is that if we shut down the entire node, then who's doing the backup? 😉 

>> Alternatively, I believe we could use sqlite online backup.

> For now I think we just want a local backup specifically for migrating the NWC app to a different machine

Just to clarify, "online" in this case doesn't mean an online service — it means a backup that happens while the database is live. SQLite can do that but we need to make sure it is properly available in the Go bindings.

**Comment by rolznz** [comment]
> The primary issue here is that if we shut down the entire node, then who's doing the backup? 😉

Hmm, just to clarify - we need to shut down any connections to LDK+BDK SQLite files, this happens automatically when we stop the node. NWC is still running. Then, we also need to shut down the connection to nwc.db, which is the service DB connection.

The NWC app should still be running at this point and still has access to the filesystem, to be able to zip the files. Since the nwc.db connection is shut down, it might be in a strange state, but I think that's ok. We don't want the user to make any changes to the DB from that point on.

**Comment by rolznz** [comment]
> Just to clarify, "online" in this case doesn't mean an online service — it means a backup that happens while the database is live. SQLite can do that but we need to make sure it is properly available in the Go bindings.

I'm not sure we want to do this because we still have to deal with LDK/BDK files. I think it's easier to just stop all DB connections and then deal with all DBs in the same way

**Comment by rdmitr** [comment]
> Since the nwc.db connection is shut down, it might be in a strange state, but I think that's ok

Yeah, that's what I was somewhat worried about. Let's see if I can make it work :)

**Comment by rdmitr** [comment]
@rolznz the work-in-progress PR is here: https://github.com/getAlby/nostr-wallet-connect-next/pull/249

It only implements backup for now. Could you please take a quick look? Does it feel like I'm moving in the right direction?

**Comment by rolznz** [comment]
@rdmitr unless I misunderstand the code, I think there are some issues with how the backup is generated. It would be nice to just have one zip file, that can be extracted back into place in the user's WORK_DIR on the new machine
