### ISSUE TITLE
"Get started" button on wallet page doesn't make sense ("I already got started")

### ISSUE THREAD

**Issue by rolznz** [getAlby/nostr-wallet-connect-next#227]
It's also confusing to me what it means. Maybe it should be - You're fully connected, now what cool things can you do? does it even make sense on the wallet page? should it be postponed for later and we add an interactive tutorial?

**Comment by reneaaron** [comment]
Agree, I recently removed it in the meantime as we don't have a better idea right now and sections to get started were added (extension + getalby.com)
