### ISSUE TITLE
Balance should reflect minimum of balance and remaining budget if a budget exists

### ISSUE THREAD

**Issue by rolznz** [getAlby/nostr-wallet-connect-next#336]
Mutiny returns only the remaining budget (for privacy) but in my opinion this makes no sense if the budget is larger than your wallet balance

**Comment by bumi** [comment]
I disagree, this just makes things more complicated and somehow apps and users have to understand this and it's not really a balance then. the name `balance` does not reflect.

**Comment by rolznz** [comment]
This idea also doesn't work so well because the wallet balance is not necessarily spendable (lightning is complex)

There are 3 main usecases here which need to be properly planned out and considered before making changes:
- external / connection-specific apps which would have an isolated budget (possibly dynamic) and isolated connection list
- global apps which can see everything and have unlimited budget (and maybe I do or don't want to see activity from external apps)
- global apps which can see everything but have a budget - currently this is also not so good because you have to execute a payment and then receive a "budget exceeded" error.
