### ISSUE TITLE
LDK: Send encrypted backup of channels to Alby API after each channel opening 

### ISSUE THREAD

**Issue by rolznz** [getAlby/nostr-wallet-connect-next#345]
In the LDK file there is a `logLdkEvent` (will be renamed to `handleLdkEvent`) which we can listen for a channel open event and call the `eventPublisher`

Inside alby.go we can consume the event and call the Alby API to save a backup of all the user's channels which will be used as a last resort if the volume the user's node is running on is somehow lost. The schema is:

`POST /internal/backups`

body: JSON `{ "description": "channels", "data": "<encrypted-backup-data-here>" }`

The data we want to send is a list of channels: the Channel ID, node ID, peer ID, channel size, funding tx ID.

The data should be encrypted using the encrypted mnemonic (this is saved in the nwc db) using the functions in `aescgm.go`.

**Comment by rdmitr** [comment]
Just to clarify, do I understand correctly that we want **all** channels backed up on every channel open event?

**Comment by rolznz** [comment]
@rdmitr yeah, the idea is to save a backup of the latest list of channels, so we know which ones to request to be closed in a disaster recovery scenario (to get the funds back that are stuck in the channels).

**Comment by rdmitr** [comment]
@rolznz the PR is up now: https://github.com/getAlby/nostr-wallet-connect-next/pull/365 — does it look about right?..
