### ISSUE TITLE
Merge app connection flows

### ISSUE THREAD

**Issue by reneaaron** [getAlby/nostr-wallet-connect-next#363]
Currently there are 2 flows how apps can be connected 
 - Connections -> New
 - Appstore -> App

Both flows work in a very similar way and should be merged code-wise to how the appstore flow works.

**Comment by rolznz** [comment]
@im-adithya are you able to help with this one? you worked on this part of the code originally

**Comment by im-adithya** [comment]
Yeah I can take this up!
