### ISSUE TITLE
Migrate remaining Alby Hosted Balance to existing channel

### ISSUE THREAD

**Issue by rolznz** [getAlby/nostr-wallet-connect-next#383]
On the liquidity page there is a card "Alby Hosted Balance" if your balance is > 100 sats.

There should be a way to move this remaining balance without opening a new channel, by sending it to one of your existing channels.

If you don't have enough liquidity, the user should be notified of this so they know what to do.

**Comment by rolznz** [comment]
Are these the same two functionalities? how do we determine to migrate to a new channel or not? based on if the amount is > 250,000 sats?

![image](https://github.com/getAlby/nostr-wallet-connect-next/assets/33993199/2ab88c6d-3fa5-401c-810d-e4f9cedbf5b1)

**Comment by bumi** [comment]
I'd say:

if there is a channel with enough (50% more?) incoming capacity we pay an invoice
if there is no channel and it's above 200k we use the pmlsp
if it's below that we tell people to deposit onchain and open a channel.
