### ISSUE TITLE
Implement backup

### ISSUE THREAD

**Issue by bumi** [getAlby/nostr-wallet-connect-next#40]
Currently the user has no option to "download" backup of the connections and the wallet data. 
We should allow the user to download a dump of the SQLite database.

**Comment by rolznz** [comment]
Also, this should be somehow uploadable in the "import" onboarding flow along with entering the backup phrase. I think without the backup all open channels would have to be force closed which would cause some pain (but at least partial recovery once the funds are returned to the wallet onchain address)

**Comment by bumi** [comment]
maybe interesting: 
https://litestream.io/

**Comment by rolznz** [comment]
https://fly.io/docs/litefs/getting-started-fly/

**Comment by rolznz** [comment]
Things user needs to back up

Things we need to backup (for LDK):
1. all the files in `.data/ldk/storage` - currently multiple bdk_wallet sqlite db files and one ldk_node_data sqlite db file.
  - If these are lost we lose all channel backups
  - this needs to be done on every payment and every change to channels
2. NWC database sqlite file
  - If these are lost we lose all app connections, payments (for budgets, analytics), request/response events (for analytics), encrypted nostr key, encrypted recovery phrase

The LDK VSS probably only solves 1.

**Comment by rolznz** [comment]
**TBC: do we need to backup the bdk files?** there are multiple and will be problematic with a tool like litestream

**Comment by rolznz** [comment]
For litestream, before starting the app I believe we would need to:
- Automate generation of a bucket and get api keys
- pass the bucket api keys to the docker file as env variables
- generate the litestream config file in the docker file flow, setting the keys and setting up the dbs (file locations and replicas using the bucket ID - for the ldk database and our NWC database)
- update the dockerfile entrypoint to be wrapped by the litestream process `litestream replicate -exec "/bin/main"`

I will test this out locally and see how it goes (everything except automating the bucket creation)

**Comment by rolznz** [comment]
- I think we still need the basic backup & restore functionality too - at least the restore functionality would be needed when the user has a way to download the backup
- We also need a way to identify a user's bucket when they request a backup. Ideally we use the Alby user identifier as the bucket name?

**Comment by rolznz** [comment]
Last update: Litestream might not be enough to reliably save channel state changes, and we might need to use a VSS.

**Comment by rolznz** [comment]
I have created new tickets as some of the my comments are outdated here
