### ISSUE TITLE
Extract SetupMnemonic page into two components

### ISSUE THREAD

**Issue by im-adithya** [getAlby/nostr-wallet-connect-next#41]
From https://github.com/getAlby/nostr-wallet-connect-next/pull/36#discussion_r1487213574
> We should split this into two components: "NewMnemonic" and "ImportMnemonic"

We should also think of removing the query parameter `?wallet=new/import`

**Comment by rolznz** [comment]
This can be done as part of moving the backup mnemonic out of the create wallet onboarding

**Comment by rolznz** [comment]
Done by @im-adithya in https://github.com/getAlby/nostr-wallet-connect-next/pull/84
