### ISSUE TITLE
Failed to connect to request invoice when buying a channel from Olympus

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/nostr-wallet-connect-next#416]
![chrome_d26eFF7AiZ](https://github.com/getAlby/nostr-wallet-connect-next/assets/13707997/2f6e94b4-0ab9-4870-b465-270c4c7de2b8)

other question: Can we actually buy a public channel from Olympus?

**Comment by rolznz** [comment]
@MoritzKa this happens if the Olympus API takes too long to respond, probably their service is under some load. I'm not sure we can do anything here except report the issue to Zeus.

We cannot buy a public channel from Olympus using their JIT API. This will be possible with LSPS1.

**Comment by MoritzKa** [comment]
Thanks Roland. 
I will close the issue.
