### ISSUE TITLE
few bugs with phoenixd backend

### ISSUE THREAD

**Issue by Funman2** [getAlby/nostr-wallet-connect-next#430]
first of all really cool app!! Kudos.

I have deployed the app as a docker container with latest version, and I have an ip like this for my phoenixd instance: http://192.168...:2121 so it always tried to connect to the default ip 127.0.0.1:9740 even if i specified my correct ip in in the nwc ui app, so initially it did not work with phoenixd, but then i added an ENV variable in the container PHOENIXD_ADDRESS=http://192.168....:2121 and then it worked. Strange...😉 lol..

Also the balance is shown as a sum of fee credit and actual balance...so i have 48 sats fee credit and 11k sats balance so Nwc-next ui wallet says i have 59k sats balance so it seems to read the fee credit as actual balance.

**Comment by bumi** [comment]
can you try again in master. I think I just fixed this. 

regarding the balance: what do you think is best to show? not show the fee credit at all? -because we can only show one balance (not two)

**Comment by Funman2** [comment]
Hi cool, will try, ....
It would be best to not show fee credit at all. Since it is not spendable balance. You can display that with phoenixd commands, anybody using phoenixd will know how to do that.... also it shows in phoenixd logs.
So best would be to display balance in alby without fee credit. 
Thanks for quick reply

**Comment by Funman2** [comment]
i think i can not try yet since i use the published docker container in my portainer app on umbrel...so that would not be updated yet i guess?

**Comment by bumi** [comment]
It should be up now. commit ef80548
https://github.com/getAlby/nostr-wallet-connect-next/pkgs/container/nostr-wallet-connect-next

**Comment by Funman2** [comment]
Yes it works now, ip and password in ui. Congrats! ...looking forward for the the fix without fee credit balance.

**Comment by Funman2** [comment]
![Bildschirmfoto vom 2024-06-12 00-10-07](https://github.com/getAlby/nostr-wallet-connect-next/assets/105175715/97a7f0ed-e18c-47eb-904c-4cfd55980a9c)
![Bildschirmfoto vom 2024-06-12 00-10-07](https://github.com/getAlby/nostr-wallet-connect-next/assets/105175715/0dfeb9c1-95a4-40e0-a384-2272aa603f3b)
here you can see the comparison between satress nwc from braydon fuller and alby

**Comment by bumi** [comment]
I am updating and not counting the fee credit

**Comment by bumi** [comment]
changed in the latest master release. 

how does it work for you? how do you like it?

**Comment by Funman2** [comment]
yes it works absolutely fine now! Thanks, like it very much! Useful for nostr.

**Comment by Funman2** [comment]
i have noticed though that wallet balance after sending does not update in linked alby nwc in browser extension, whereas with braydons satdress nwc it instantly updates...

**Comment by bumi** [comment]
yes, there is a bit of caching to increase the speed.
we need to tweak this a bit
