### ISSUE TITLE
review and re-enable multiplatform docker workflow

### ISSUE THREAD

**Issue by rolznz** [getAlby/nostr-wallet-connect-next#478]
I think this is needed for Umbrel and Start9 releases when we have them. The build is failing currently and only runs on:
```
  release:
    types: [published]
```

which is inconsistent with our other workflows (not that it is necessarily wrong, just needs review).

**Comment by rdmitr** [comment]
This should be fixed by https://github.com/getAlby/nostr-wallet-connect-next/pull/501

As for the Github action trigger, it seems appropriate to run this action on release. It is quite slow, so running it only when a release is published makes sense.
