### ISSUE TITLE
Send events to Alby API (such as node restarted so user knows they need to unlock their node)

### ISSUE THREAD

**Issue by bumi** [getAlby/nostr-wallet-connect-next#52]
It might be that the app restarts (for whatever reason). In that case the user has to unlock the app again to start the wallet. 
Right now we do not notify the user about this and the user might wonder why things don't work. 

We should notify the user in that case. 
by: 

+ by nostr DM
+ by email

Email has the problem that some email server is needed.

**Comment by rolznz** [comment]
Also we need notifications for e.g. closed channels, otherwise balance and channels "disappear" with no notice

**Comment by rolznz** [comment]
Idea: send simple posthog-style events (event name and properties?) to the Alby API which then can decide how to notify the user and when (e.g. by email after 3 failed payments).
