### ISSUE TITLE
Add extra API endpoints to make it easier to debug things

### ISSUE THREAD

**Issue by rolznz** [getAlby/nostr-wallet-connect-next#63]
I would like to do things as a developer for things that are not already exposed in the UI without creating a complex UI such as:
- probing routes without paying (SendPaymentProbes and SendSpontaneousPaymentProbes)
- list peers
- retrieve last 1000 lines of logs from the app **TBC**
- retrieve last 1000 lines of logs from the LDK node **TBC**

These should be implemented the same way as our current http endpoints (like to list channels or get the onchain balance)

The UI should be as minimal as possible (or non-existent if we could e.g. do it through browser devtools - would need to confirm that works in Wails mode)

*We only need to expose functions that are not already exposed (e.g. ListChannels already exists - we just need to update it to return all channel info and then we can inspect the response in the network tab)* **TBC: this will not work in Wails mode**

**Comment by rdmitr** [comment]
Could you please elaborate a bit on the use case for probes in this issue? Right now LDK has an API method called `send_payment_probes()` but it doesn't return any information (payment hashes/IDs), only error code on failure.

Do we need to enhance the LDK bindings to return more payment info?

**Comment by rolznz** [comment]
@rdmitr I think we need to look at the LDK logs to get more information after executing the function, unfortunately.

**Comment by rdmitr** [comment]
@rolznz we can change the function to return more information but I need to know what exactly we need :)

**Comment by rdmitr** [comment]
WIP PR here: https://github.com/getAlby/nostr-wallet-connect-next/pull/123
