### ISSUE TITLE
Cannot setup new LDK node if ldk directory already exists

### ISSUE THREAD

**Issue by rolznz** [getAlby/nostr-wallet-connect-next#71]
Storage is saved for the current LDK node and cannot be used with a different mnemonic. Either the old ldk folder needs to be removed, or we could generate a folder name based off a short hash of the mnemonic

Ideally eventually we manage all storage in one place for easier backup/restore.

**Comment by bumi** [comment]
is this a problem now? when would you run the app and then change the seed?

**Comment by bumi** [comment]
I would say we make a backup option to download every thing and then we also add a complete reset option?

**Comment by rolznz** [comment]
Closing in favor of https://github.com/getAlby/nostr-wallet-connect-next/issues/40
