### ISSUE TITLE
Use more standard data directory for wails

### ISSUE THREAD

**Issue by rolznz** [getAlby/nostr-wallet-connect-next#91]
We should use the OS-provided user profile data directory rather than a .data file in the directory where the app is run (which is problematic when updating / running from a different location etc)

**Comment by rolznz** [comment]
I saw there was https://freshman.tech/snippets/go/home-directory/ 

Is this what you meant @bumi ?

**Comment by bumi** [comment]
yes, maybe something like this one: https://github.com/adrg/xdg

and we get the config dir and write to `/alby/nwc-desktop` or something like that.

**Comment by rdmitr** [comment]
PR is up now. I chose to use data dir instead of the config dir, since we don't really store config there 🤔
